### PR TITLE
DB Seed 

### LINKED ISSUE #39: Seed file
Reseed the DB with fake users/questions/answers

### PR DESCRIPTION
**Pull request by Code-zart**
closes #39

### CODE REVIEW

**Comment by Code-zart** [comment]
I can't seem to fix this right now, I must have accidentally changed something. When I get it running again I'll push up the adjustment.

**Comment by Code-zart** [comment]
It's fixed. Good to go!

**Comment by ErnieAtLYD** [comment]
@Stommy123 wanna confirm Moshe's changes are correct here?

**Comment by Code-zart** [comment]
Issues fixed, seed file working

**Pull request merged**
